# Generated by Django 3.2.15 on 2022-08-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_surname', models.CharField(max_length=50)),
                ('address_p', models.TextField()),
                ('price_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_month', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone_p', models.CharField(max_length=20)),
                ('mail_p', models.EmailField(max_length=254)),
                ('country_p', models.CharField(max_length=30)),
                ('city_p', models.CharField(max_length=30)),
                ('slots', models.IntegerField()),
                ('avalaible', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_surname', models.CharField(max_length=50)),
                ('phone_u', models.CharField(max_length=20)),
                ('mail_u', models.EmailField(max_length=254)),
                ('country_u', models.CharField(max_length=30)),
                ('city_u', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.users')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking')),
            ],
        ),
    ]
