# Generated by Django 3.2.15 on 2022-08-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='car_plate',
            field=models.CharField(default='sin confirmar', max_length=20),
        ),
    ]
