# Generated by Django 3.2.15 on 2022-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_users_car_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='url_map',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
