# Generated by Django 3.2.15 on 2022-08-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
        ('reserves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='parkings',
            field=models.ManyToManyField(through='reserves.ReserveParkings', to='parking.Parking'),
        ),
    ]
