# Generated by Django 3.2.15 on 2022-08-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('price_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_week', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_year', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.IntegerField()),
                ('avalaible', models.BooleanField(default=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]