# Generated by Django 3.2.15 on 2022-08-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tikets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiket',
            name='tiket_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
